### ISSUE TITLE
Add `get_unchecked`

### ISSUE THREAD

**Issue by Tnze** [TudbuT/micro_ndarray#1]
Sometimes we need faster `get` methods.

**Comment by TudbuT** [comment]
Should be pretty straightforward. I'll get to it some time today or tomorrow.

**Comment by TudbuT** [comment]
Would you want to give the index into the data array directly, or still have that be computed? Maybe have both?

**Comment by Tnze** [comment]
From my personal needs, I think it's the latter. If I don't need to calculate the index, I can just use `Vec`.

**Comment by TudbuT** [comment]
Added and published as 0.2.4.
