### ISSUE TITLE
`Array::new_with()` shouldn't require `Default` to be satisfied for `T`

### ISSUE THREAD

**Issue by Tnze** [TudbuT/micro_ndarray#5]
https://github.com/TudbuT/micro_ndarray/blob/24a3a8eb01075fda655260add8bf65886146b0f0/src/array.rs#L31-L45

**Comment by TudbuT** [comment]
Yep, that's correct, thanks! Fix will be pushed within the hour.

**Comment by TudbuT** [comment]
There ya go, sorry for the trouble!

**Comment by Tnze** [comment]
Thank you very much
